[passwords]
# Follow the rule: username = "password"
finetune = "genai@2024"
bob_bar = "mycrazypw"

[connections.postgresql]
dialect = "postgresql"
host = "finetune-ai.postgres.database.azure.com"
port = "5432"
database = "Fintune"
username = "finetune"
password = "genai#2024"

[database]
credentials  = '''{
  "type": "service_account",
  "project_id": "project-sirius-424906",
  "private_key_id": "57e8f6a85fe08ddba5a1aadebc65704a8ac348d3",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCa1TYW4RuKOENy\njare4FCf8ObjlYaMDBte+xu1vF9y6+vKKRWOAVEBLQahawmAq5XvQIFByHwfGbE0\nWLq5fH9qF/jJGFrE4tlD52eVhn6z6QoDk3jj0j/4BPdUebtrh63rd6uR+Ln/ETWG\nrVBv66/wJzgjhvk3quSKk3ZYRhnqHGYF7+o4QZKigIdUg4yjbgckplNfRWkKBlLf\nYnmP1O27f5VU9SbyfrPuEJ9G0V8SWgOy5Yo17jcWa6VDn/MxZoiVuzomnqHB2Dwp\nKGyVnGbdrUHGYg9AORoOzBDrAc8bTSexUZqjDhX6CfZevc2sV6Uk5n8Y5dWLAkMM\nEg6oc+nzAgMBAAECggEAAJpTlMDj9GSmBT7+SyeGGNaoHNBluYuIhb+mNXhvdLPs\nyJjir8QF4TfK0/u7NJLhHrvaZPusrrWmZiTxoSxAwL8pevr1y4NzQ3DrYH5+usuY\nUY2URcAj+0llqcte3/B4zGG8ZhvuTssYhsGLqSE6n6LqHzVKKMh+YvhnrbikJtsG\nO2r2NvY11jn5ewDEenEJImFhpz9hNFbXk5G+5Nx1FKkqf7BVBRfotqZiys+43LoS\nRIZFWSce48P7o5TP5Nhgo/bDJ4r3R54mWVBVHeMkRJ2lIuFbUqo9ItBJo9yaTa3t\nocKEv/EnkzNSaGd3Gsyiv6TwwPQMZkod4BY1se4zUQKBgQDPysLCZTATybFobc++\nswFAQTDH+HsNs1ATojWHVgkfruvNSlZN/wTNiXYzHrTcuryLHdFTaQuvMFNFGIS9\nz1xM/4PgbFQAeHs3CmsDHBvJnn1qOPL3fdEYUwTG5c/rA9fHiOhUS7BNCPLx/EhR\nmbBu2nK1zlJExRZhPpHQ6q+VgwKBgQC+wRXHwUCEQtfGeBgmWevH+dmAvN74zIyH\nZVFEjbfMQivzU9yBkxEV0lxx+nLIdHEqZg3SDHTMPCtdw1E+FlsCj0p2A75ZzbKq\nXG0Nn14DUlYMMtAJ2+15PJuGvDboqF18j+5ddLlmQ/Z4M8RmPLdiJ1DGOIyF5lgR\nwWBbB5ye0QKBgG179UB+FmXmuM5ARdzB7p/PeYdz2kput3uQ1Ul4wJfsD5x8VZsF\nCp/NlPT8cel3js5yKJAdYiWtfcKDV7W3I3gCjZbbHSueT7XBjH73+YAzPPuSBBr5\nNQnu/C5cej/nJ3OgJGH9+2erlm6AMg6kvvy5pwU6L8jCW7djQ2tjrJ5HAoGAK/oN\n0GigPB3A6zOitazDa+4RE9n3ObrGpyxXiQt3FTMoOMfbrU+/f51ozKolrksSD+lJ\nRGS0xKUWhl5SK5Mx1iw8yWphhwiiKR530c0s+m0QA23vgmZeoDW10WEw84BlVSNF\nm+weFhKTDvE4VS2oRYu01o4Q74nEQgun8DSYChECgYEAypzH9Dd8cT2gXWbT9OtO\nc+lmBm87pzxxIZn4nLztPIMlStPhVhrfGYVMubCkG1t+4+NywPgWVMiIrsQKLJvu\n27mQNRI28D+fIRJJmrHuRTU0ovI+q3MbswXOLiqaEOmzXnaydBrTb6TloIPnQUqC\nIBdhic89MV+G3Du9XDV5cnI=\n-----END PRIVATE KEY-----\n",
  "client_email": "sairam-service-account@project-sirius-424906.iam.gserviceaccount.com",
  "client_id": "115827079310941287252",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sairam-service-account%40project-sirius-424906.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}'''
connection_string = "postgresql://postgres:postgres-genai@34.93.64.44/genai"